//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientoVehiculos.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MantenimientoVehiculos.Web.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next component change in the next 100.
        /// </summary>
        public static string ChangeOver100 {
            get {
                return ResourceManager.GetString("ChangeOver100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        public static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component to change.
        /// </summary>
        public static string ComponentChangeMessage {
            get {
                return ResourceManager.GetString("ComponentChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component doesn&apos;t exists..
        /// </summary>
        public static string ComponetDoesntExists {
            get {
                return ResourceManager.GetString("ComponetDoesntExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Confirmation email was sent. Please confirm your account and log into the App..
        /// </summary>
        public static string ConfirmEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To allow the user, please click on this link:.
        /// </summary>
        public static string ConfirmEmailSubject {
            get {
                return ResourceManager.GetString("ConfirmEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date..
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed Next Change.
        /// </summary>
        public static string ExecutedNextChange {
            get {
                return ResourceManager.GetString("ExecutedNextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect current password..
        /// </summary>
        public static string IncorrectCurrentPassword {
            get {
                return ResourceManager.GetString("IncorrectCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Type.
        /// </summary>
        public static string MaintenanceType {
            get {
                return ResourceManager.GetString("MaintenanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field can not have more than {1} characters..
        /// </summary>
        public static string MaxLength_Message {
            get {
                return ResourceManager.GetString("MaxLength_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification Date..
        /// </summary>
        public static string ModificationDate {
            get {
                return ResourceManager.GetString("ModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Change Km Hr.
        /// </summary>
        public static string NextChangeKmHr {
            get {
                return ResourceManager.GetString("NextChangeKmHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password was changed successfully!.
        /// </summary>
        public static string PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Password.
        /// </summary>
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email with instructions to change the password was sent..
        /// </summary>
        public static string RecoverPasswordMessage {
            get {
                return ResourceManager.GetString("RecoverPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reset the password click in this link:.
        /// </summary>
        public static string RecoverPasswordSubject {
            get {
                return ResourceManager.GetString("RecoverPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register activity &apos;Km/Hours&apos;.
        /// </summary>
        public static string RegisterActivity {
            get {
                return ResourceManager.GetString("RegisterActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is mandatory..
        /// </summary>
        public static string Required_Message {
            get {
                return ResourceManager.GetString("Required_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to Live.
        /// </summary>
        public static string TTL {
            get {
                return ResourceManager.GetString("TTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists..
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t exists..
        /// </summary>
        public static string UserDoesntExists {
            get {
                return ResourceManager.GetString("UserDoesntExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified by.
        /// </summary>
        public static string UserModified {
            get {
                return ResourceManager.GetString("UserModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
    }
}
